### ISSUE TITLE
Requests - Event Source/Type 

### ISSUE THREAD

**Issue by ImpactInsights** [ImpactInsights/valuestream#51]
Please put all Event Source / Type requests here! This should allow us to centralize and vote for them. 

Thank you!

**Comment by ImpactInsights** [comment]
Trello

**Comment by ImpactInsights** [comment]
Jira Sprint Issues (Default Swimlanes)

**Comment by dm03514** [comment]
Asana

**Comment by dm03514** [comment]
Clubhouse

**Comment by ImpactInsights** [comment]
Jenkins - [Groovy Event Listener](https://github.com/jenkinsci/groovy-events-listener-plugin)
