### ISSUE TITLE
GitHub: Performance Report

### ISSUE THREAD

**Issue by dm03514** [ImpactInsights/valuestream#53]
It would be really cool to generate a GitHub performance report which details time spent in Pull Requests, and issues for a given repo.

- Rate of issues closed 
- Duration of issues closed by label
- Pull Requests Rate Open / Closed
- Pull Request duration

**Comment by dm03514** [comment]
## Github Pull Request Report

```
$ go run cmd/vsperformancereport/main.go github -org=ImpactInsights -repo=valuestream -max-page=2
```

**Comment by dm03514** [comment]
<img width="1462" alt="Screen Shot 2020-01-19 at 8 55 56 AM" src="https://user-images.githubusercontent.com/321963/72682288-8b517480-3a99-11ea-8ae8-f50b306aef92.png">

<img width="1547" alt="Screen Shot 2020-01-19 at 8 55 31 AM" src="https://user-images.githubusercontent.com/321963/72682289-8d1b3800-3a99-11ea-818d-beadda52821d.png">

**Comment by ascipio** [comment]
Hi @dm03514 , thanks for great analysis tool. How to change this command for local repositories?  "go run cmd/vsperformancereport/main.go github -org=ImpactInsights -repo=valuestream -access-token="" -max-page=2 > ~/Documents/eng_metrics/impactinsights.csv"
