### ISSUE TITLE
Quickstart broken due to Jaeger 1.18

### ISSUE THREAD

**Issue by cyorja** [ImpactInsights/valuestream#70]
Running the HTTP step of the quickstart did not produce results.
Ran "docker-compose up" and ngrok and configured the webhook.  Pull requests and issues were logged in the ngrok terminal, but did not appear in Jaeger.

On inspection, the jaeger-agent was failing to startup and aborting with message
  "unknown flag: --collector.host-port"
This was not showing up in the "docker-compose logs -f valuestream" terminal but did show up when I ran the "docker-compose up" without the "-d" argument.

Seems that jaeger-agent's  "--collector.host-port" argument doesn't appear in any Jaeger documentation beyond 1.17.  Modified the docker-compose.yml to peg the Jaeger components to 1.17 instead of "latest" and the quickstart worked.

**Comment by dm03514** [comment]
Thank you so much

https://github.com/ImpactInsights/valuestream/pull/71

**Comment by rantonucci-washpost** [comment]
Sticking a question in here as I don't see any support line.  I noticed in the quickstart that you start up a kibana container.  Do you actually have a dashboard configured as part of the quickstart?  Would love to see it.
