### ISSUE TITLE
Github Enterprise projects

### ISSUE THREAD

**Issue by justin-segler** [ImpactInsights/valuestream#72]
Is there a way to utilize valuestream for a Github Enterprise project? As of right now, I am not finding that queries are able to find my organization. I'm assuming that this is due to the generic Github API being leveraged rather than the Github Enterprise API being leveraged. Are there future goals to adapt valuestream to be accessible via the Github Enterprise API such that valuestream can access data from Github Enterprise projects if it isn't already possible? Thanks!

**Comment by clcpolevaulter** [comment]
+1 I'd love more information on this.

**Comment by dm03514** [comment]
Ah sorry about the long response. Could you please post some more information about what you’re seeing? I’m not familiar with github’s enterprise offering. Based on the information you provided I’m assuming it’s a completely different set of endpoints? 

If possible could you please provide an example request and the response you’re seeing? 

Value stream uses go-github client library so hopefully it’s as simple as accepting another command line flag -is-enterprise , or something, and using the appropriate endpoints. 

Perhaps github even provides a metadata endpoint and we can figure out the type of token and use the correct api (enterprise vs public) without needing an additional flag.

**Comment by clcpolevaulter** [comment]
I changed the following lines and the PR report worked fine. 

``` go
return githubv4.NewEnterpriseClient("https://{mygithubdomain}/api/graphql", tc)
```

https://github.com/ImpactInsights/valuestream/blob/7719d878bf885e2a4fd0d1c4f2acbbc4a6834b13/eventsources/github/report.go#L21

**Comment by dm03514** [comment]
Perfect, I should be able to add support for this tomorrow!

**Comment by dm03514** [comment]
@clcpolevaulter @justin-segler sorry about this "tomorrow" turned into 4 weeks. 

I added supporting using the strategy that you outlined @clcpolevaulter but was unable to test with real data.

The CLI accepts a new flag called:

```
-enterprise-domain=mygithubdomain
```

The value of this will be used to build the Enterprise URL:

```
return githubv4.NewEnterpriseClient("https://{mygithubdomain}/api/graphql", tc)
```

**Comment by dm03514** [comment]
I'm closing this issue, please let me know if you encounter any problems and I can reopen and address.
