### ISSUE TITLE
Media

### ISSUE THREAD

**Issue by ImpactInsights** [ImpactInsights/valuestream#8]

**Comment by ImpactInsights** [comment]
https://drive.google.com/open?id=18yxxy0GLaDjFp9a2OLU6XcLpNLOgWkZB

**Comment by ImpactInsights** [comment]
<img width="1448" alt="Screen Shot 2019-07-14 at 5 34 52 PM" src="https://user-images.githubusercontent.com/53025024/61565404-ed77e100-aa46-11e9-89f7-56ba7ba694ad.png">
![issue_deploy](https://user-images.githubusercontent.com/53025024/61565406-ef41a480-aa46-11e9-8ca8-6e663a4e524c.png)

**Comment by ImpactInsights** [comment]
![issue_deploy](https://user-images.githubusercontent.com/53025024/61565413-f7014900-aa46-11e9-99d6-d42907c8fd54.png)

**Comment by dm03514** [comment]
![vs_abstracted_metrics](https://user-images.githubusercontent.com/321963/70324408-69f43c00-17fd-11ea-9b81-9b247f8b78cf.png)

**Comment by dm03514** [comment]
![vs_events](https://user-images.githubusercontent.com/321963/70324841-8cd32000-17fe-11ea-80fc-7587da9120a4.png)

**Comment by dm03514** [comment]
![vs_traces](https://user-images.githubusercontent.com/321963/70324842-8f357a00-17fe-11ea-84fb-69d4dd076ed9.png)
